apiVersion: v1 
kind: Namespace 
metadata:
  name: sai
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: sai
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: <redacted>
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 32Mi
            cpu: 20m
          requests:
            memory: 32Mi
            cpu: 20m          
---
apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: sai
spec:
  selector:
    app: server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-hpa
  namespace: sai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10